backend:
  name: github
  repo: IYAOAA/1000HomeVibes
  branch: main
  base_url: https://decapcms-oauth.vercel.app
  auth_endpoint: auth
  app_id: Ov23li4fqzVzlUlSVUhH

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Title", name: "title", widget: "string" }
      - { label: "Product ID", name: "id", widget: "string" }
      - { label: "Image URL", name: "image", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Air", "Sleep", "Body"] }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Buy Link", name: "buy_link", widget: "string" }